---
- name: Déployer un site web statique
  hosts: webservers
  become: yes
  
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Arrêter Apache2 (s'il existe)
      service:
        name: apache2
        state: stopped
        enabled: no
      ignore_errors: yes
    
    - name: Supprimer tous les fichiers par défaut
      shell: rm -rf /var/www/html/*
    
    - name: Copier notre site web
      copy:
        src: ./website/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: S'assurer que Nginx est démarré
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted
