---
- name: Déployer un site web
  hosts: webservers
  become: true

  tasks:
    - name: Supprimer la page par défaut nginx
      file:
        path: /var/www/html/index.nginx-debian.html
        state: absent

    - name: Copier notre site
      copy:
        src: website/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: 0644
    - name: Redémarrer Apache
      systemd:
        name: apache2
        state: restarted

